name: Publish to GitHub Pages

on:
  push:
    tags:
      - "v*"

jobs:
  main:
    name: Publish to GitHub Pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Publish to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false